spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: gabperez.exito@gmail.com
    password: boeijsufhwzddddt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000